a = '   _~_    '
b = '  (o o)   '
c = ' /  V  \\  '
d = '/(  _  )\\ '
e = '  ^^ ^^   '
request = int(input("Введите число пингвинчиков от 1 до 9:"))
print(request * a, sep=' ')
print(request * b, sep=' ')
print(request * c, sep=' ')
print(request * d, sep=' ')
print(request * e, sep=' ')